<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE results [
  <!ELEMENT results (#PCDATA|pagination|subtitle)*>
    <!ELEMENT pagination (current, count, results)>
      <!ELEMENT current (#PCDATA)>
      <!ELEMENT count (#PCDATA)>
    <!ELEMENT subtitle (id, title, year, movieId, url, uploaderId, uploaderName, release, releases, languageId, languageName, time, tvSeason, tvEpisode, tvSpecial, cds, format, fps, rating, flags, downloads)>
      <!ELEMENT id (#PCDATA)>
      <!ELEMENT pid (#PCDATA)>
      <!ELEMENT title (#PCDATA)>
      <!ELEMENT year (#PCDATA)>
      <!ELEMENT movieId (#PCDATA)>
      <!ELEMENT url (#PCDATA)>
      <!ELEMENT uploaderId (#PCDATA)>
      <!ELEMENT uploaderName (#PCDATA)>
      <!ELEMENT releases (release)>
        <!ELEMENT release (#PCDATA)>
      <!ELEMENT languageId (#PCDATA)>
      <!ELEMENT languageName (#PCDATA)>
      <!ELEMENT language (#PCDATA)>
      <!ELEMENT time (#PCDATA)>
      <!ELEMENT tvSeason (#PCDATA)>
      <!ELEMENT tvEpisode (#PCDATA)>
      <!ELEMENT tvSpecial (#PCDATA)>
      <!ELEMENT cds (#PCDATA)>
      <!ELEMENT format (#PCDATA)>
      <!ELEMENT fps (#PCDATA)>
      <!ELEMENT rating (#PCDATA)>
      <!ELEMENT flags (#PCDATA)>
      <!ELEMENT new_flags (flag)>
        <!ELEMENT flag (#PCDATA)>
      <!ELEMENT downloads (#PCDATA)>
      <!ELEMENT exactHashes (#PCDATA)>]> <results><pagination><current>1</current><count>2</count><results>35</results></pagination><subtitle><id>4327755</id><pid>SwlC</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/fa-the-flash-2014-S03E03/SwlC</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.x264-LOL The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA The.Flash.2014.S03E03.480p.HDTV.x264-mSD The.Flash.2014.S03E03.XviD-AFG The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam The.Flash.2014.S03E03.HDTV.XviD-AFG The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG The.Flash.2014.S03E03.HDTV.XviD-FUM</release><releases><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-mSD</release><release>The.Flash.2014.S03E03.XviD-AFG</release><release>The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam</release><release>The.Flash.2014.S03E03.HDTV.XviD-AFG</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG</release><release>The.Flash.2014.S03E03.HDTV.XviD-FUM</release></releases><languageId>52</languageId><languageName>Farsi</languageName><language>fa</language><time>1477415017</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>0</downloads><exactHashes /></subtitle><subtitle><id>4326861</id><pid>zQVC</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/nl-the-flash-2014-S03E03/zQVC</url><uploaderId>None</uploaderId><uploaderName /><release>The Flash S03E03 Magenta HDTV The.Flash.2014.S03E03.XviD-AFG The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><releases><release>The Flash S03E03 Magenta HDTV</release><release>The.Flash.2014.S03E03.XviD-AFG</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release></releases><languageId>23</languageId><languageName>Dutch</languageName><language>nl</language><time>1477321656</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>1676</downloads><exactHashes /></subtitle><subtitle><id>4326041</id><pid>mQJC</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/si-the-flash-2014-S03E03/mQJC</url><uploaderId>178129</uploaderId><uploaderName>nkadissanayake</uploaderName><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The Flash S03E03 The.Flash.2014.S03E03.HDTV.x264-LOL</release><releases><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The Flash S03E03</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release></releases><languageId>56</languageId><languageName>Sinhala</languageName><language>si</language><time>1477234238</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>0</downloads><exactHashes /></subtitle><subtitle><id>4326010</id><pid>egJC</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/it-the-flash-2014-S03E03/egJC</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.x264-DIMENSION The.Flash.2014.S03E03.HDTV.x264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><releases><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.x264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release></releases><languageId>9</languageId><languageName>Italian</languageName><language>it</language><time>1477231385</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>26</downloads><exactHashes /></subtitle><subtitle><id>4326008</id><pid>eAJC</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/it-the-flash-2014-S03E03/eAJC</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG The.Flash.2014.S03E03.WEB-DL The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release><releases><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG</release><release>The.Flash.2014.S03E03.WEB-DL</release><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release></releases><languageId>9</languageId><languageName>Italian</languageName><language>it</language><time>1477231054</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>37</downloads><exactHashes /></subtitle><subtitle><id>4324464</id><pid>cPxB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/pl-the-flash-2014-S03E03/cPxB</url><uploaderId>94818</uploaderId><uploaderName>Pati1989</uploaderName><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release><releases><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG</release><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release></releases><languageId>26</languageId><languageName>Polish</languageName><language>pl</language><time>1477066507</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags>h</flags><new_flags><flag>high_definition</flag></new_flags><downloads>84</downloads><exactHashes /></subtitle><subtitle><id>4324256</id><pid>oPtB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/fi-the-flash-2014-S03E03/oPtB</url><uploaderId>269557</uploaderId><uploaderName>Anonyym</uploaderName><release>The.Flash.2014.S03E03.HDTV.x264 The.Flash.2014.S03E03.XviD-AFG The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><releases><release>The.Flash.2014.S03E03.HDTV.x264</release><release>The.Flash.2014.S03E03.XviD-AFG</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release></releases><languageId>31</languageId><languageName>Finnish</languageName><language>fi</language><time>1477052099</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>57</downloads><exactHashes /></subtitle><subtitle><id>4323559</id><pid>5_hB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/fa-the-flash-2014-S03E03/5_hB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.x264-LOL The.Flash.2014.S03E03.720p.HDTV.x265.HEVC-ONMKV The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA The.Flash.2014.S03E03.480p.HDTV.x264-mSD The.Flash.2014.S03E03..720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam The.Flash.2014.S03E03.HDTV.XviD-AFG The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG The.Flash.2014.S03E03.HDTV.XviD-FUM</release><releases><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.x265.HEVC-ONMKV</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam</release><release>The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-mSD</release><release>The.Flash.2014.S03E03..720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam</release><release>The.Flash.2014.S03E03.HDTV.XviD-AFG</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG</release><release>The.Flash.2014.S03E03.HDTV.XviD-FUM</release></releases><languageId>52</languageId><languageName>Farsi</languageName><language>fa</language><time>1476983366</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>0</downloads><exactHashes /></subtitle><subtitle><id>4323557</id><pid>5fhB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/id-the-flash-2014-S03E03/5fhB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The Flash (2016) Episode 03 HDTV 720p | Malay Subtitle The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.XviD-AFG</release><releases><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The Flash (2016) Episode 03 HDTV 720p | Malay Subtitle</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.XviD-AFG</release></releases><languageId>54</languageId><languageName>Indonesian</languageName><language>id</language><time>1476983224</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>8</downloads><exactHashes /></subtitle><subtitle><id>4323510</id><pid>tvhB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/es-the-flash-2014-S03E03/tvhB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.S03E03.Magenta.DIMENSION The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.S03E03.Magenta.LOL The.Flash.2014.S03E03.XviD-AFG The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.S03E03.Magenta.WEB-DL</release><releases><release>The.Flash.S03E03.Magenta.DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.S03E03.Magenta.LOL</release><release>The.Flash.2014.S03E03.XviD-AFG</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.S03E03.Magenta.WEB-DL</release></releases><languageId>28</languageId><languageName>Spanish</languageName><language>es</language><time>1476979089</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>616</downloads><exactHashes /></subtitle><subtitle><id>4323476</id><pid>lPhB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/da-the-flash-2014-S03E03/lPhB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG The.Flash.S03E03.WEB-DL.x264-RARBG The.Flash.S03E03.Custom.DKsubs.720p.WEB-DL.H.264-RELEASED The.Flash.S03E03.Custom.DKsubs.720p.WEB-DL.H.264-RELEASED_track1_dan The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release><releases><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG</release><release>The.Flash.S03E03.WEB-DL.x264-RARBG</release><release>The.Flash.S03E03.Custom.DKsubs.720p.WEB-DL.H.264-RELEASED</release><release>The.Flash.S03E03.Custom.DKsubs.720p.WEB-DL.H.264-RELEASED_track1_dan</release><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release></releases><languageId>24</languageId><languageName>Danish</languageName><language>da</language><time>1476975441</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>152</downloads><exactHashes /></subtitle><subtitle><id>4323438</id><pid>bvhB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/ar-the-flash-2014-S03E03/bvhB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H.264-DRACULA The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H.264-DRACULA</release><releases><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H.264-DRACULA</release><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H.264-DRACULA</release></releases><languageId>12</languageId><languageName>Arabic</languageName><language>ar</language><time>1476972864</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>96</downloads><exactHashes /></subtitle><subtitle><id>4323429</id><pid>ZfhB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/id-the-flash-2014-S03E03/ZfhB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.S03E03.Magenta.HDTV.X264.UPILGORILLA The-Flash-S03E03-Magenta-HDTV-X264-UPILGORILLA</release><releases><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.S03E03.Magenta.HDTV.X264.UPILGORILLA</release><release>The-Flash-S03E03-Magenta-HDTV-X264-UPILGORILLA</release></releases><languageId>54</languageId><languageName>Indonesian</languageName><language>id</language><time>1476972386</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>0</downloads><exactHashes /></subtitle><subtitle><id>4323427</id><pid>Y_hB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/ar-the-flash-2014-S03E03/Y_hB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H.264-DRACULA The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H.264-DRACULA</release><releases><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H.264-DRACULA</release><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H.264-DRACULA</release></releases><languageId>12</languageId><languageName>Arabic</languageName><language>ar</language><time>1476972384</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>27</downloads><exactHashes /></subtitle><subtitle><id>4323357</id><pid>HfhB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/vi-the-flash-2014-S03E03/HfhB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.720p.HDTV.x264-DIMENSION The.Flash.2014.S03E03.HDTV.x264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.x264 The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.x264-LOL The.Flash.2014.S03E03.HDTV.X264-LOL</release><releases><release>The.Flash.2014.S03E03.720p.HDTV.x264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.x264</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release></releases><languageId>51</languageId><languageName>Vietnamese</languageName><language>vi</language><time>1476968781</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>60</downloads><exactHashes /></subtitle><subtitle><id>4323373</id><pid>LfhB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/sl-the-flash-2014-S03E03/LfhB</url><uploaderId>214264</uploaderId><uploaderName>denycare</uploaderName><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.XviD-AFG The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><releases><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.XviD-AFG</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release></releases><languageId>1</languageId><languageName>Slovenian</languageName><language>sl</language><time>1476968672</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>1.0</rating><flags>ha</flags><new_flags><flag>high_definition</flag><flag>author</flag></new_flags><downloads>328</downloads><exactHashes /></subtitle><subtitle><id>4323323</id><pid>-_dB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/id-the-flash-2014-S03E03/-_dB</url><uploaderId>None</uploaderId><uploaderName /><release>The-Flash-S03E03-Magenta-Semua-WEB-DL-ReivanoDiegoDelaVega The.Flash.2014.S03E03.Magenta.720p.WEB-DL.5.1CH.x264-TooN</release><releases><release>The-Flash-S03E03-Magenta-Semua-WEB-DL-ReivanoDiegoDelaVega</release><release>The.Flash.2014.S03E03.Magenta.720p.WEB-DL.5.1CH.x264-TooN</release></releases><languageId>54</languageId><languageName>Indonesian</languageName><language>id</language><time>1476965188</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>22</downloads><exactHashes /></subtitle><subtitle><id>4322920</id><pid>aPZB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/fa-the-flash-2014-S03E03/aPZB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03..720p.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.x264-LOL The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA The.Flash.2014.S03E03.480p.HDTV.x264-mSD The.Flash.2014.S03E03.All.WEB-DL The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam The.Flash.2014.S03E03.HDTV.XviD-AFG The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION.Fa The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.HDTV.XviD-FUM</release><releases><release>The.Flash.2014.S03E03..720p.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam</release><release>The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-mSD</release><release>The.Flash.2014.S03E03.All.WEB-DL</release><release>The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam</release><release>The.Flash.2014.S03E03.HDTV.XviD-AFG</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION.Fa</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.HDTV.XviD-FUM</release></releases><languageId>52</languageId><languageName>Farsi</languageName><language>fa</language><time>1476911789</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>3</downloads><exactHashes /></subtitle><subtitle><id>4322911</id><pid>X_ZB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/fa-the-flash-2014-S03E03/X_ZB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03..720p.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.x264-LOL The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA The.Flash.2014.S03E03.480p.HDTV.x264-mSD The.Flash.2014.S03E03.All.WEB-DL The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam The.Flash.2014.S03E03.HDTV.XviD-AFG The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG The.Flash.2014.S03E03.HDTV.XviD-FUM</release><releases><release>The.Flash.2014.S03E03..720p.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam</release><release>The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-mSD</release><release>The.Flash.2014.S03E03.All.WEB-DL</release><release>The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam</release><release>The.Flash.2014.S03E03.HDTV.XviD-AFG</release><release>The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG</release><release>The.Flash.2014.S03E03.HDTV.XviD-FUM</release></releases><languageId>52</languageId><languageName>Farsi</languageName><language>fa</language><time>1476911185</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>0</downloads><exactHashes /></subtitle><subtitle><id>4322910</id><pid>XvZB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/ar-the-flash-2014-S03E03/XvZB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.x264-LOL The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam The.Flash.2014.S03E03.HDTV.XviD-AFG The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.XviD-iFT The.Flash.2014.S03E03.HDTV.XviD-FUM</release><releases><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam</release><release>The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA</release><release>The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG</release><release>The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam</release><release>The.Flash.2014.S03E03.HDTV.XviD-AFG</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.XviD-iFT</release><release>The.Flash.2014.S03E03.HDTV.XviD-FUM</release></releases><languageId>12</languageId><languageName>Arabic</languageName><language>ar</language><time>1476910829</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>115</downloads><exactHashes /></subtitle><subtitle><id>4322881</id><pid>QfZB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/ar-the-flash-2014-S03E03/QfZB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.HDTV.X264-LOL The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.x264-LOL The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam The.Flash.2014.S03E03.HDTV.XviD-AFG The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.480p.HDTV.x264-mSD The.Flash.2014.S03E03.HDTV.XviD-FUM</release><releases><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.x264-LOL</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-RMTeam</release><release>The.Flash.2014.S03E03.720p.HDTV.2CH.x265.HEVC-PSA</release><release>The.Flash.2014.S03E03.720p.HDTV.x265.ShAaNiG</release><release>The.Flash.2014.S03E03.720p.HDTV.HEVC.x265-RMTeam</release><release>The.Flash.2014.S03E03.HDTV.XviD-AFG</release><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.480p.HDTV.x264-mSD</release><release>The.Flash.2014.S03E03.HDTV.XviD-FUM</release></releases><languageId>12</languageId><languageName>Arabic</languageName><language>ar</language><time>1476906751</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags /><new_flags /><downloads>189</downloads><exactHashes /></subtitle><subtitle><id>4322815</id><pid>__VB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/en-the-flash-2014-S03E03/__VB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release><releases><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG</release><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release></releases><languageId>2</languageId><languageName>English</languageName><language>en</language><time>1476903431</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags>nh</flags><new_flags><flag>hearing_impaired</flag><flag>high_definition</flag></new_flags><downloads>3162</downloads><exactHashes /></subtitle><subtitle><id>4322816</id><pid>APZB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/en-the-flash-2014-S03E03/APZB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release><releases><release>The.Flash.2014.S03E03.1080p.WEB-DL.DD5.1.H264-RARBG</release><release>The.Flash.2014.S03E03.720p.WEB-DL.DD5.1.H264-RARBG</release></releases><languageId>2</languageId><languageName>English</languageName><language>en</language><time>1476903428</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpisode><tvSpecial>0</tvSpecial><cds /><format>N/A</format><fps>N/A</fps><rating>0.0</rating><flags>h</flags><new_flags><flag>high_definition</flag></new_flags><downloads>4538</downloads><exactHashes /></subtitle><subtitle><id>4322747</id><pid>u_VB</pid><title>The Flash</title><year>2014</year><movieId>y-cG</movieId><url>http://www.podnapisi.net/subtitles/fr-the-flash-2014-S03E03/u_VB</url><uploaderId>None</uploaderId><uploaderName /><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION The.Flash.2014.S03E03.HDTV.X264-LOL</release><releases><release>The.Flash.2014.S03E03.1080p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.720p.HDTV.X264-DIMENSION</release><release>The.Flash.2014.S03E03.HDTV.X264-LOL</release></releases><languageId>8</languageId><languageName>French</languageName><language>fr</language><time>1476899706</time><tvSeason>3</tvSeason><tvEpisode>3</tvEpiso